import React from 'react';
import {
  Sparkles,
  CheckCircle2,
  Lock,
  Play,
  ArrowRight,
  Zap,
  Activity,
  Layers,
  BookOpen,
  Award
} from 'lucide-react';
import { LearningPathNode, ViewRoute } from '../types';
import { learningPathNodesData } from '../data/mockData';

interface LearningPathViewProps {
  nodes?: LearningPathNode[];
  onNavigate: (route: ViewRoute) => void;
}

export const LearningPathView: React.FC<LearningPathViewProps> = ({
  nodes = learningPathNodesData,
  onNavigate
}) => {
  return (
    <div className="w-full min-h-[calc(100vh-4rem)] p-4 sm:p-6 lg:p-8 max-w-5xl mx-auto space-y-6">
      {/* Header */}
      <div className="p-6 sm:p-8 rounded-2xl bg-gradient-to-b from-slate-900 via-slate-950 to-slate-950 border border-indigo-500/30 shadow-2xl space-y-3 relative overflow-hidden">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 text-xs font-semibold">
            <Zap className="w-3.5 h-3.5" />
            <span>Mastery Knowledge Graph & Adaptive Progression</span>
          </div>
          <span className="text-xs font-mono text-cyan-400">Class 10 Physics • Chapter 4</span>
        </div>

        <h1 className="text-2xl sm:text-3xl font-heading font-extrabold text-white">
          Electricity — Interactive Learning Roadmap
        </h1>
        <p className="text-xs sm:text-sm text-slate-300 max-w-2xl leading-relaxed">
          Your personalized prerequisite graph generated by the AI Teacher. Complete nodes to unlock higher-tier conceptual problems.
        </p>
      </div>

      {/* Roadmap Tree Node List */}
      <div className="relative pl-6 sm:pl-8 space-y-6 before:absolute before:left-3 sm:before:left-4 before:top-4 before:bottom-4 before:w-0.5 before:bg-gradient-to-b before:from-emerald-500 before:via-indigo-500 before:to-slate-800">
        {nodes.map((node, index) => {
          const isCompleted = node.status === 'completed';
          const isInProgress = node.status === 'active';
          const isLocked = node.status === 'locked';

          return (
            <div
              key={node.id}
              className={`relative p-5 rounded-2xl border transition-all duration-300 ${
                isInProgress
                  ? 'bg-gradient-to-r from-indigo-950/50 via-slate-900 to-slate-900 border-indigo-500 shadow-xl shadow-indigo-500/10 ring-1 ring-indigo-400/40 scale-[1.01]'
                  : isCompleted
                  ? 'bg-slate-900/90 border-emerald-500/30 shadow-md'
                  : 'bg-slate-950/60 border-slate-900 opacity-60'
              }`}
            >
              {/* Connector Node Dot */}
              <div
                className={`absolute -left-[30px] sm:-left-[38px] top-6 w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold shadow-lg transition-all ${
                  isCompleted
                    ? 'bg-emerald-500 text-slate-950'
                    : isInProgress
                    ? 'bg-indigo-600 text-white ring-4 ring-indigo-500/30 animate-pulse'
                    : 'bg-slate-800 text-slate-500 border border-slate-700'
                }`}
              >
                {isCompleted ? '✓' : isLocked ? <Lock className="w-3.5 h-3.5" /> : index + 1}
              </div>

              {/* Node Content */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div className="space-y-1.5 max-w-xl">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="font-mono text-xs font-bold text-slate-500">
                      Module 0{index + 1}
                    </span>
                    <h3 className="text-base font-bold text-white font-heading">
                      {node.title}
                    </h3>
                    <span
                      className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase tracking-wider ${
                        isCompleted
                          ? 'bg-emerald-500/20 text-emerald-300'
                          : isInProgress
                          ? 'bg-indigo-500/20 text-indigo-300'
                          : 'bg-slate-800 text-slate-400'
                      }`}
                    >
                      {node.status.replace('_', ' ')}
                    </span>
                  </div>

                  <p className="text-xs text-slate-400 leading-relaxed">
                    {node.description}
                  </p>

                  {/* Prerequisites */}
                  {node.prerequisites.length > 0 && (
                    <div className="flex items-center gap-1.5 text-[11px] text-slate-500 pt-1">
                      <span>Prerequisites:</span>
                      <span className="font-mono text-slate-400">
                        {node.prerequisites.join(', ')}
                      </span>
                    </div>
                  )}
                </div>

                {/* Right side stats & action */}
                <div className="flex flex-row sm:flex-col items-center sm:items-end justify-between gap-2 shrink-0">
                  <div className="text-right">
                    <span className="text-[10px] uppercase font-bold text-slate-500 block">
                      Mastery
                    </span>
                    <span
                      className={`text-base font-extrabold font-mono ${
                        isCompleted
                          ? 'text-emerald-400'
                          : isInProgress
                          ? 'text-indigo-400'
                          : 'text-slate-600'
                      }`}
                    >
                      {node.masteryPercentage}%
                    </span>
                  </div>

                  {!isLocked && (
                    <button
                      type="button"
                      onClick={() => onNavigate('teacher')}
                      className={`flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                        isInProgress
                          ? 'bg-indigo-600 hover:bg-indigo-500 text-white shadow-md shadow-indigo-600/30'
                          : 'bg-slate-800 hover:bg-slate-700 text-slate-200'
                      }`}
                    >
                      <Play className="w-3 h-3 fill-current" />
                      <span>{isInProgress ? 'Resume' : 'Review'}</span>
                    </button>
                  )}
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
